SUBJECT_ID_KEY = 'SubjectID'
ASSIGNMENT_ID_KEY = 'AssignmentID'
MID_SCORE_KEY = 'MID_Score'
INCREMENTAL_KEY = 'Incremental' # boolean key in df, <=2.5 Incremental, >2.5 Non-Incremental
ASSIGNMENT_SCORE_KEY = 'AssignmentScore'
FINAL_SCORE_KEY = 'FinalScore'
CLIENT_TIMESTAMP_KEY = 'ClientTimestamp'

DATE_TIME_KEY = 'DateTime'
NEXT_DATE_TIME_KEY = 'NextDateTime'
DIFF_KEY = 'Diff'
DAYS_DIFF_KEY = 'DaysDiff'
HOURS_DIFF_KEY = 'HoursDiff'
MINUTES_DIFF_KEY = 'MinutesDiff'
SECONDS_DIFF_KEY = 'SecondsDiff'
SESSION_ID_KEY = 'SessionID'
SESSION_TIME_KEY = 'SessionTimeMs'
TOTAL_ASSIGNMENT_TIME_KEY = 'TotalAssignmentTimeMs'
